name: cypress test

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run project frontend
        run: cd my-svelte-project
             npm run dev
      - name: change to cypress file
        run:  cd frontend_testing
              npx cypress run

        
